#!/usr/bin/env bash
# One-shot, idempotent deployment of sciscrap for Hermes Agent (WSL2 Ubuntu / Linux).
#
#   bash hermes_deploy.sh [--email you@example.com] [--out /mnt/c/Users/Me/Papers] [--dir ~/Sciscrap] [--no-mcp]
#
# What it does:
#   1. clones (or updates) the repo, creates a venv, installs sciscrap (+ MCP extras)
#   2. installs a `sciscrap` command in ~/.local/bin with your defaults baked in
#   3. installs the Hermes skill in ~/.hermes/skills/research/sciscrap
#   4. registers the sciscrap MCP server in ~/.hermes/config.yaml (backup kept)
#   5. verifies: search, one real PDF download, MCP server import
# The last line printed is either "DEPLOY_OK ..." or "DEPLOY_FAILED ...".
set -uo pipefail

REPO_URL="${SCISCRAP_REPO:-https://github.com/ikhanai777/Sciscrap.git}"
BRANCH="${SCISCRAP_BRANCH:-claude/sci-hub-paper-scraper-gjilqf}"
DIR="$HOME/Sciscrap"
EMAIL="${SCISCRAP_EMAIL:-}"
OUT="${SCISCRAP_OUT:-}"
MCP=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --email) EMAIL="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    --dir) DIR="$2"; shift 2 ;;
    --no-mcp) MCP=0; shift ;;
    *) echo "unknown option: $1"; exit 2 ;;
  esac
done

step() { echo; echo "==> $*"; }
fail() { echo; echo "DEPLOY_FAILED step=\"$1\" reason=\"$2\""; exit 1; }

# ---------------------------------------------------------------- 0. prerequisites
step "Checking prerequisites"
need=()
command -v git >/dev/null || need+=(git)
command -v python3 >/dev/null || need+=(python3)
python3 -c "import venv, ensurepip" 2>/dev/null || need+=(python3-venv)
if [[ ${#need[@]} -gt 0 ]]; then
  echo "Installing: ${need[*]}"
  if command -v apt-get >/dev/null; then
    sudo -n true 2>/dev/null || fail prerequisites "need sudo to install ${need[*]}; run: sudo apt-get install -y git python3 python3-venv python3-pip"
    sudo apt-get update -qq && sudo apt-get install -y -qq git python3 python3-venv python3-pip || fail prerequisites "apt-get install failed"
  else
    fail prerequisites "please install: ${need[*]}"
  fi
fi
python3 -c "import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)" \
  || fail prerequisites "Python 3.10+ required, found $(python3 --version 2>&1)"
echo "ok: $(python3 --version), $(git --version)"

# ---------------------------------------------------------------- 1. code + venv
step "Getting sciscrap into $DIR"
if [[ -d "$DIR/.git" ]]; then
  git -C "$DIR" fetch -q origin "$BRANCH" || fail clone "git fetch failed (network?)"
  git -C "$DIR" checkout -q "$BRANCH" 2>/dev/null || git -C "$DIR" checkout -q -b "$BRANCH" "origin/$BRANCH"
  git -C "$DIR" merge -q --ff-only "origin/$BRANCH" || echo "warning: local changes in $DIR; not updated"
else
  git clone -q -b "$BRANCH" "$REPO_URL" "$DIR" || fail clone "git clone $REPO_URL failed"
fi
cd "$DIR" || fail clone "cannot cd to $DIR"
echo "ok: $(git log --oneline -1)"

step "Creating virtualenv and installing"
[[ -x .venv/bin/python ]] || python3 -m venv .venv || fail install "python3 -m venv failed"
.venv/bin/python -m pip install -q --upgrade pip || fail install "pip upgrade failed"
if [[ $MCP == 1 ]]; then
  .venv/bin/python -m pip install -q -e ".[mcp]" || fail install "pip install -e .[mcp] failed"
else
  .venv/bin/python -m pip install -q -e . || fail install "pip install -e . failed"
fi
echo "ok: $(.venv/bin/sciscrap --version)"

# ---------------------------------------------------------------- 2. defaults + command
step "Configuring defaults"
WRAPPER="$HOME/.local/bin/sciscrap"
if [[ -f "$WRAPPER" && ! -L "$WRAPPER" ]]; then   # re-run: keep values from the previous deploy
  prev() { sed -n "s/^export $1=\"\\\${$1:-\(.*\)}\"$/\1/p" "$WRAPPER"; }
  [[ -z "$OUT" ]] && OUT="$(prev SCISCRAP_OUT)"
  [[ -z "$EMAIL" ]] && EMAIL="$(prev SCISCRAP_EMAIL)"
fi
WINUSER=""
if command -v cmd.exe >/dev/null 2>&1; then
  WINUSER="$(cd /mnt/c 2>/dev/null; cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r\n')"
fi
if [[ -z "$OUT" ]]; then
  if [[ -n "$WINUSER" && -d "/mnt/c/Users/$WINUSER" ]]; then
    OUT="/mnt/c/Users/$WINUSER/Papers"   # visible in Windows as C:\Users\<user>\Papers
  else
    OUT="$HOME/Papers"
  fi
fi
mkdir -p "$OUT" || fail configure "cannot create $OUT"
echo "ok: download folder = $OUT"
[[ -n "$EMAIL" ]] && echo "ok: contact email = $EMAIL" || echo "note: no --email given (optional; enables Unpaywall)"

mkdir -p "$HOME/.local/bin"
rm -f "$WRAPPER"   # setup_wsl.sh may have left a symlink; never write through it into the venv
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by sciscrap/scripts/hermes_deploy.sh. Defaults can be overridden by env vars or flags.
export SCISCRAP_OUT="\${SCISCRAP_OUT:-$OUT}"
export SCISCRAP_EMAIL="\${SCISCRAP_EMAIL:-$EMAIL}"
exec "$DIR/.venv/bin/sciscrap" "\$@"
EOF
chmod +x "$WRAPPER"
if [[ $MCP == 1 ]]; then
  rm -f "$HOME/.local/bin/sciscrap-mcp"
  ln -s "$DIR/.venv/bin/sciscrap-mcp" "$HOME/.local/bin/sciscrap-mcp"
fi
if ! grep -q '# sciscrap PATH' "$HOME/.bashrc" 2>/dev/null; then
  printf '\n# sciscrap PATH\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$HOME/.bashrc"
fi
export PATH="$HOME/.local/bin:$PATH"
echo "ok: command installed at $WRAPPER"

# ---------------------------------------------------------------- 3. Hermes skill
step "Installing Hermes skill"
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
SKILL_DIR="$HERMES_HOME/skills/research/sciscrap"
mkdir -p "$SKILL_DIR"
sed -e "s#\`~/Sciscrap/.venv/bin/sciscrap\` (WSL/Linux)#\`$WRAPPER\` (installed here)#" \
    -e "s#Default download folder: \`\$SCISCRAP_OUT\` if set, otherwise pass \`--out\`.#Default download folder on this machine: \`$OUT\` (used automatically when --out is omitted).#" \
    hermes/skills/sciscrap/SKILL.md > "$SKILL_DIR/SKILL.md" || fail skill "cannot write $SKILL_DIR/SKILL.md"
echo "ok: $SKILL_DIR/SKILL.md"

# ---------------------------------------------------------------- 4. Hermes MCP server
MCP_STATUS="skipped"
if [[ $MCP == 1 ]]; then
  step "Registering MCP server in $HERMES_HOME/config.yaml"
  mkdir -p "$HERMES_HOME"
  MCP_STATUS="$(.venv/bin/python - "$HERMES_HOME/config.yaml" "$DIR/.venv/bin/sciscrap-mcp" "$OUT" "$EMAIL" <<'PY'
import re, shutil, sys, time
from pathlib import Path
cfg, cmd, out, email = Path(sys.argv[1]), *sys.argv[2:]
text = cfg.read_text(encoding="utf-8") if cfg.exists() else ""
if re.search(r"(?m)^\s+sciscrap:\s*$", text) and "sciscrap-mcp" in text:
    print("already-registered"); sys.exit()
block = (
    "  sciscrap:\n"
    f"    command: {cmd}\n"
    "    args: []\n"
    "    env:\n"
    f"      SCISCRAP_OUT: \"{out}\"\n"
    f"      SCISCRAP_EMAIL: \"{email}\"\n"
    "    timeout: 3600\n"
)
if cfg.exists():
    shutil.copy2(cfg, cfg.with_name(f"config.yaml.bak-{time.strftime('%Y%m%d-%H%M%S')}"))
m = re.search(r"(?m)^mcp_servers:[ \t]*(\{\s*\}|null|~)?[ \t]*$", text)
if m:
    # Insert our entry right under the existing "mcp_servers:" line (other servers stay below it).
    rest = text[m.end():]
    text = text[:m.start()] + "mcp_servers:\n" + block + (rest[1:] if rest.startswith("\n") else rest)
elif re.search(r"(?m)^mcp_servers:", text):
    print("manual-needed"); sys.exit()   # unusual inline form; don't risk corrupting it
else:
    text = text.rstrip("\n") + ("\n\n" if text.strip() else "") + "mcp_servers:\n" + block
cfg.write_text(text, encoding="utf-8")
print("registered")
PY
)" || MCP_STATUS="error"
  echo "result: $MCP_STATUS"
  if [[ "$MCP_STATUS" == "manual-needed" || "$MCP_STATUS" == "error" ]]; then
    echo "Add this under mcp_servers: in $HERMES_HOME/config.yaml by hand:"
    echo "  sciscrap:"
    echo "    command: $DIR/.venv/bin/sciscrap-mcp"
    echo "    args: []"
    echo "    timeout: 3600"
  fi
fi

# ---------------------------------------------------------------- 5. verify
step "Verifying"
sciscrap --version >/dev/null 2>&1 || fail verify "sciscrap command does not run"
echo "ok: sciscrap command runs"

if sciscrap search "CRISPR Cas9 genome editing" -n 3 --json > /tmp/sciscrap_search.json 2>/dev/null \
   && .venv/bin/python -c "import json,sys; d=json.load(open('/tmp/sciscrap_search.json')); sys.exit(0 if d and d[0]['doi'] else 1)"; then
  SEARCH="ok"
else
  SEARCH="failed"
fi
echo "search: $SEARCH"

TEST_DIR="$OUT/_sciscrap_test"
DL_JSON="$(sciscrap get 10.1038/nature12373 --out "$TEST_DIR" --json 2>/dev/null)"
PDF="$(echo "$DL_JSON" | .venv/bin/python -c "import json,sys; r=json.load(sys.stdin)['results'][0]; print(r['file'] if r['status'] in ('downloaded','exists') else '')" 2>/dev/null)"
if [[ -n "$PDF" && "$(head -c 5 "$PDF" 2>/dev/null)" == "%PDF-" ]]; then
  DOWNLOAD="ok"
  rm -rf "$TEST_DIR"
else
  DOWNLOAD="failed"
  echo "download output: $(echo "$DL_JSON" | head -c 600)"
fi
echo "download: $DOWNLOAD"

if [[ $MCP == 1 ]]; then
  .venv/bin/python -c "import sciscrap.mcp_server" 2>/dev/null && MCP_IMPORT="ok" || MCP_IMPORT="failed"
  echo "mcp server: $MCP_IMPORT"
else
  MCP_IMPORT="skipped"
fi

echo
if [[ $DOWNLOAD == ok || $SEARCH == ok ]]; then
  echo "DEPLOY_OK dir=$DIR out=$OUT command=$WRAPPER skill=$SKILL_DIR mcp=$MCP_STATUS search=$SEARCH download=$DOWNLOAD mcp_import=$MCP_IMPORT"
  echo "Restart Hermes (exit and run \`hermes\` again) so it loads the new skill and MCP server."
else
  fail verify "search=$SEARCH download=$DOWNLOAD (network blocked? try again later or check proxy/firewall)"
fi
